### ISSUE TITLE
download 

### ISSUE THREAD

**Issue by Saman37** [soshika/fastmovie#14]
dar bakhshe detailse movies dar ghesmate download (quality - size - va linke download) pishfarz neshon mide

**Comment by soshika** [comment]
@Saman37 in yekam tulanie revalesh taqriban 3-4 saati zaman mibare dorost konam esh

**Comment by soshika** [comment]
@Saman37 ino fix kardam feqat bayad test konam esh
bayad dl haye server tamom she server ro update konam bad test konam esh
